name: 'Github Repository Metadata'
description: 'Github Action exposes useful metadata as environment variable which can be called / used in a workflow'
author: 'varunsridharan'
branding:
  icon: 'database'
  color: 'yellow'

inputs:
  repository:
    description: 'Custom Repository To Fetch Information For'
    required: false
    default: false
  debug:
    description: 'Set True To Show Debug Messages'
    required: false
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'