name: 'Github Repository Metadata'
description: 'Github Action exposes useful metadata as environment variable which can be called / used in a workflow'
author: 'varunsridharan'
branding:
  icon: 'database'
  color: 'yellow'
runs:
  using: 'docker'
  image: 'Dockerfile'
