name: "Test"

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '*/60 * * * *'


jobs:
  self_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: "Metadata For Self"
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remote_repo_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: "Metadata For wponion/wponion"
        uses: ./
        with:
          REPOSITORY: wponion/wponion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}