name: "Test"

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/60 * * * *'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository Metadata Test
        uses: varunsridharan/action-repository-meta@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
