name: "🧪 Test"

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

jobs:
  linux:
    name: "🧪  Linux"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾   Metadata For Self"
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💾   Metadata For wponion/wponion"
        uses: ./
        with:
          REPOSITORY: wponion/wponion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    name: "🧪  Windows"
    runs-on: windows-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾   Metadata For Self"
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💾   Metadata For wponion/wponion"
        uses: ./
        with:
          REPOSITORY: wponion/wponion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: "🧪  macOS"
    runs-on: windows-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾   Metadata For Self"
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💾   Metadata For wponion/wponion"
        uses: ./
        with:
          REPOSITORY: wponion/wponion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}